receivers:

  otlp:
    protocols:
      grpc:
        endpoint: otel_collector:4318
      http:
        endpoint: otel_collector:4317

exporters:

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]