version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.4.2-alpine
    networks:
      - inst-java-apps-using-otel
    ports:
      - "9000:9000"
      - "8123:8123"

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16685:16685"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"

  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.102.0
    volumes:
      - ./collector-config.yml:/etc/otelcol/collector-config.yml
    command: --config /etc/otelcol/collector-config.yml
    depends_on:
      - jaeger
    networks:
      - inst-java-apps-using-otel
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # otlp receiver grpc
      - "4318:4318"   # otlp receiver http
      - "55679:55679" # zpages extension

  service-layer:
    build: .
    networks:
      - inst-java-apps-using-otel
    depends_on:
      - otel_collector
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_INSTRUMENTATION_HTTP_CLIENT_EMIT_EXPERIMENTAL_TELEMETRY=true
      - OTEL_INSTRUMENTATION_HTTP_SERVER_EMIT_EXPERIMENTAL_TELEMETRY=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel_collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_IMR_EXPORT_INTERVAL=5000
      - OTEL_SERVICE_NAME=omsvclyr
      - OTEL_METRIC_EXPORT_INTERVAL=5000
      - OTEL_RESOURCE_ATTRIBUTES="job=job,application=omsvclyr,service.name=service-layer,service.version=1.0,deployment.environment=development"

networks:
  inst-java-apps-using-otel:
    driver: bridge
    name: inst-java-apps-using-otel